In [1]:
# Importing libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
# Reading in the panda dataframe
coffee_set = pd.read_csv("data/Coffee_Data")
coffee_set.head()

,Unnamed: 0,Country.of.Origin,Number.of.Bags,Bag.Weight,Aroma,Flavor,Aftertaste,Acidity,Body,Balance,...,Sweetness,Cupper.Points,Total.Cup.Points,Moisture,Category.One.Defects,Quakers,Category.Two.Defects,altitude_low_meters,altitude_high_meters,altitude_mean_meters
0,0,Ethiopia,300,60 kg,8.67,8.83,8.67,8.75,8.50,8.42,...,10.0,8.75,90.58,0.12,0,0.0,0,1950.0,2200.0,2075.0
1,1,Ethiopia,300,60 kg,8.75,8.67,8.50,8.58,8.42,8.42,...,10.0,8.58,89.92,0.12,0,0.0,1,1950.0,2200.0,2075.0
2,2,Guatemala,5,1,8.42,8.50,8.42,8.42,8.33,8.42,...,10.0,9.25,89.75,0.00,0,0.0,0,1600.0,1800.0,1700.0
3,3,Ethiopia,320,60 kg,8.17,8.58,8.42,8.42,8.50,8.25,...,10.0,8.67,89.00,0.11,0,0.0,2,1800.0,2200.0,2000.0
4,4,Ethiopia,300,60 kg,8.25,8.50,8.25,8.50,8.42,8.33,...,10.0,8.58,88.83,0.12,0,0.0,2,1950.0,2200.0,2075.0

In [3]:
# Need to fixe index column so going to make Unamed the index
coffee_set.set_index("Unnamed: 0", inplace = True)

In [4]:
# Seeing if chnage took
coffee_set.head()

,Country.of.Origin,Number.of.Bags,Bag.Weight,Aroma,Flavor,Aftertaste,Acidity,Body,Balance,Uniformity,...,Sweetness,Cupper.Points,Total.Cup.Points,Moisture,Category.One.Defects,Quakers,Category.Two.Defects,altitude_low_meters,altitude_high_meters,altitude_mean_meters
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
0,Ethiopia,300,60 kg,8.67,8.83,8.67,8.75,8.50,8.42,10.0,...,10.0,8.75,90.58,0.12,0,0.0,0,1950.0,2200.0,2075.0
1,Ethiopia,300,60 kg,8.75,8.67,8.50,8.58,8.42,8.42,10.0,...,10.0,8.58,89.92,0.12,0,0.0,1,1950.0,2200.0,2075.0
2,Guatemala,5,1,8.42,8.50,8.42,8.42,8.33,8.42,10.0,...,10.0,9.25,89.75,0.00,0,0.0,0,1600.0,1800.0,1700.0
3,Ethiopia,320,60 kg,8.17,8.58,8.42,8.42,8.50,8.25,10.0,...,10.0,8.67,89.00,0.11,0,0.0,2,1800.0,2200.0,2000.0
4,Ethiopia,300,60 kg,8.25,8.50,8.25,8.50,8.42,8.33,10.0,...,10.0,8.58,88.83,0.12,0,0.0,2,1950.0,2200.0,2075.0

In [5]:
# Change == "Worked"

In [6]:
# Converting the Country.of.Origin to binary
# Ethiopia is 1 and Guatemala is 0
coffee_set["Country.of.Origin"] = np.where(coffee_set["Country.of.Origin"] == "Ethiopia", 1, 0)

In [7]:
# Making sure the chnage took
coffee_set.head()

,Country.of.Origin,Number.of.Bags,Bag.Weight,Aroma,Flavor,Aftertaste,Acidity,Body,Balance,Uniformity,...,Sweetness,Cupper.Points,Total.Cup.Points,Moisture,Category.One.Defects,Quakers,Category.Two.Defects,altitude_low_meters,altitude_high_meters,altitude_mean_meters
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
0,1,300,60 kg,8.67,8.83,8.67,8.75,8.50,8.42,10.0,...,10.0,8.75,90.58,0.12,0,0.0,0,1950.0,2200.0,2075.0
1,1,300,60 kg,8.75,8.67,8.50,8.58,8.42,8.42,10.0,...,10.0,8.58,89.92,0.12,0,0.0,1,1950.0,2200.0,2075.0
2,0,5,1,8.42,8.50,8.42,8.42,8.33,8.42,10.0,...,10.0,9.25,89.75,0.00,0,0.0,0,1600.0,1800.0,1700.0
3,1,320,60 kg,8.17,8.58,8.42,8.42,8.50,8.25,10.0,...,10.0,8.67,89.00,0.11,0,0.0,2,1800.0,2200.0,2000.0
4,1,300,60 kg,8.25,8.50,8.25,8.50,8.42,8.33,10.0,...,10.0,8.58,88.83,0.12,0,0.0,2,1950.0,2200.0,2075.0

In [8]:
# Change == "Worked"